language: groovy
jdk:
- openjdk8
sudo: required
before_install:
- wget -O cf-linux.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
- tar xvfz cf-linux.tgz
- chmod 755 ./cf
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then
  ./deploy ; fi
notifications:
  slack:
    secure: RvtFRYLJCJCgJKBlGdLl/d2Hc8bTE+eqLSn1ZLJWrrDRU8H3t6A98WPzWA8Q3WgcwtaybKKCkhSoyxWC9HJyAkQaD03eAkrQRn9i8hm4H3fbDJ56mEL0VM5DvhLrqnyJqTBzM80X+0BeMKt0iEhiSabRK+nmJGiVHZG/Zup83cNahDtf0h617RPIks4tnAn3pspLnhxIVgSEXGBAOPc/nZMLQSQH9d428Wz88R+TfvBGLBEx8mGKZK0Zh8wy+AWJAxKhS4vGTm5cfAgpuptb5Ik3IFWBpmVNxj7M01vRNLb6gv4uVFUSKxWUL7UZYfI2Pn2cZhne9Exo2TVcY6rJxe4osj0JWyhBrKu2vnynVUmHcLKhaDzW6AKJp4xZY8DTix7QBRVFxNuq7YZrRwprYcKqSlZFNyKwE7vzpMvSuYgOpS0YzT+t19ELWAOZMD3STryKalRxwfYnnHM9nf3a1VCAvIa5a2nbSdanKDgvBaAkVeQr/aXOdXsdMYsQ3eCyNytoRFzqn80TSVpoTvzXrk1LydSZmp6VFlKmmXkR6a0vMJA6bcXePUD/g7K4Xwg+BIXC2tgV5y4lmrjiWTysiQAShqzpKkivOzKRE1xycv4t/ByMgzhbJohsz0pdlK0DaSSeVURlnjYmiFrNtSdzJQGKD0cOTjrWme9/hOllWAg=
