#!/bin/bash -x

set -euo pipefail

# Login to PWS
/cf api https://api.run.pivotal.io

/cf auth ${PWS_USR} ${PWS_PSW}

# Target spring.io and deploy
/cf target -o spring.io -s Guides

/cf push slackboot -p target/slackboot-*.jar