#!/bin/bash -x

set -euo pipefail

ls -ld /.cf

# Login
/cf api https://api.sc2-04-pcf1-system.oc.vmware.com
/cf auth ${PWS_USR} ${PWS_PSW}

# Target spring.io and deploy
/cf target -o Spring -s spring-guides
/cf push slackboot -p target/slackboot-*.jar
