image:https://travis-ci.com/spring-io/slackboot.svg?token=W7aHg1sSsP4krxEgwMRV&branch=master["Build Status", link="https://travis-ci.com/spring-io/slackboot"]

This bot is used to help manage the guides and tutorials at https://spring.io/guides.

This bot is also a nice demo app for building Slack bots.

=== Running CI tasks locally

Since the pipeline uses Docker, it's easy to:

* Debug what went wrong on your local machine.
* Test out a a tweak to your `test.sh` script before sending it out.
* Experiment against a new image before submitting your pull request.

All of these use cases are great reasons to essentially run what Jenkins does on your local machine.

IMPORTANT: To do this you must have Docker installed on your machine.

1. `docker run -it --mount type=bind,source="$(pwd)",target=/slackboot-github springci/slackboot:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-hateoas-github`.
+
2. `cd slackboot-github`
+
Next, run the `test.sh` script from inside the container:
+
2. `./mvnw package`

Since the container is binding to your source, you can make edits from your IDE and continue to run build jobs.

NOTE: Docker containers can eat up disk space fast! From time to time, run `docker system prune` to clean out old images.

