logging:
  level:
    io:
      spring:
        slackboot:
          commands:
            PingSlackCommand: DEBUG
          core:
            DeadmanSwitch: DEBUG
            PingingService: DEBUG
            services:
              SlackService: DEBUG
